services:
  api:
    build: .
    ports:
      - "5001:5000" # Container port:Host port
    environment:
      # TODO: change to production - this will disable graphql sandbox for security
      - NODE_ENV=development
      - PORT=5000
    env_file:
      - .env.docker
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Database service
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: caselaw_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 
